//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public string Cheif { get; set; }
        public int Capacity { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}
