//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsBuy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsBuy()
        {
            this.Repairs = new HashSet<Repairs>();
        }
    
        public int ID { get; set; }
        public string GoodsID { get; set; }
        public System.DateTime DateBuy { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Goods Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repairs> Repairs { get; set; }
    }
}
